description: >
  Prepare the nix build environment

steps:
  - nix/install
  - run:
      name: Build nix environment
      command: |
        sudo -i nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
        sudo -i nix-channel --update nixpkgs
        mkdir ~/.config/nixpkgs
        echo '{ allowUnfree = true; }' >> ~/.config/nixpkgs/config.nix
        nix-shell -p cachix --run "cachix use cuda-maintainers"
      no_output_timeout: 1800s
