version: 2.1

orbs:
  sp-orb: sourcepoint/sp-orb@x.y

commands:

jobs:
  build_and_test:
    executor: sp-orb/sp_standard_executor
    steps:
      - checkout
      # perform build and test here
      - sp-orb/slack_notify:
          branch_pattern: main
          event: fail
          git_url: << pipeline.project.git_url >>
          header: "Failed to build/test :red_circle:"

  build_and_push_docker_to_ecr:
    executor: sp-orb/sp_standard_executor
    steps:
      - checkout
      # create docker image and push to ecr here
      - sp-orb/sp_slack_notify:
          branch_pattern: main
          event: fail
          git_url: << pipeline.project.git_url >>
          header: "ECR push failed :red_circle:"
      - sp-orb/sp_slack_notify:
          branch_pattern: main
          event: pass
          git_url: << pipeline.project.git_url >>
          header: "ECR push succeeded :white_check_mark:"

workflows:
  version: 2
  ci_build:
    jobs:
      - build_and_test:
          # add context here
      - sp-orb/ready_to_build_docker_on_hold_notification:
          git_url: << pipeline.project.git_url >>
          filters:
            branches:
              only: main
          # add context here
          requires:
            - build_and_test
      - prompt_build_docker:
          filters:
            branches:
              only: main
          requires:
            - build_and_test
            - sp-orb/ready_to_build_docker_on_hold_notification
          type: approval
      - build_and_push_docker_to_ecr:
          filters:
            branches:
              only: main
          # add context here
          requires:
            - prompt_build_docker
      - sp-orb/ready_to_deploy_docker_on_hold_notification:
          git_url: << pipeline.project.git_url >>
          filters:
            branches:
              only: main
          # add context here
          requires:
            - build_and_push_docker_to_ecr
      - prompt_deploy_production:
          filters:
            branches:
              only: main
          requires:
            - build_and_push_docker_to_ecr
            - sp-orb/ready_to_deploy_docker_on_hold_notification
          type: approval
      - sp-orb/k8s_deploy_production:
          git_url: << pipeline.project.git_url >>
          resource_name: deployment/k8_resource_name_goes_here
          namespace: k8_namespace_goes_here
          filters:
            branches:
              only: main
          # add context here
          requires:
            - prompt_deploy_production
      - prompt_deploy_staging:
          filters:
            branches:
              only: main
          requires:
            - build_and_push_docker_to_ecr
            - sp-orb/ready_to_deploy_docker_on_hold_notification
          type: approval
      - sp-orb/k8s_deploy_staging:
          git_url: << pipeline.project.git_url >>
          resource_name: deployment/k8_resource_name_goes_here
          namespace: k8_namespace_goes_here
          filters:
            branches:
              only: main
          # add context here
          requires:
            - prompt_deploy_staging
